version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: production
    container_name: backend-test
    networks:
      - test-network

  frontend:
    build: 
      context: ./frontend
      target: production
      args:
        - ENVIRONMENT=docker
    container_name: frontend-test
    depends_on:
      - backend
    networks:
      - test-network

  e2e:
    build:
      context: ./frontend
      dockerfile: Dockerfile-e2e
    environment:
      - PLAYWRIGHT_TEST_BASE_URL=http://frontend-test:80
    volumes:
      - ./frontend/test-results:/app/test-results
      - ./frontend/playwright-report:/app/playwright-report
    depends_on:
      - frontend
      - backend
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
