version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: production
    container_name: backend
    ports:
      - "8081:9428"
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9428/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      target: production
      args:
        - ENVIRONMENT=docker
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
