module.exports = [
  {
    userId: "1",
    name: "Eli KOPTER",
    age: "9",
    icon: "red_fish.png",
    conditions: ["Dyslexia", "ADHD"],
    userConfig: {
      showsAnswer: true,
      addition: true,
      subtraction: true,
      multiplication: true,
      division: true,
      rewrite: true,
      encryption: true,
      word: true,
    },
    musicEnabled: false,
    effectsEnabled: true,
  },
  {
    userId: "2",
    name: "Judas BRICOT",
    age: "9",
    icon: "yellow_fish.png",
    conditions: ["Dyscalculia"],
    userConfig: {
      showsAnswer: true,
      addition: true,
      subtraction: true,
      multiplication: false,
      division: false,
      rewrite: true,
      encryption: false,
      word: false,
    },
    musicEnabled: true,
    effectsEnabled: true,
  },
  {
    userId: "3",
    name: "Lucie FERT",
    age: "9",
    icon: "blue_fish.png",
    conditions: [],
    userConfig: {
      showsAnswer: false,
      addition: true,
      subtraction: true,
      multiplication: true,
      division: true,
      rewrite: true,
      encryption: true,
      word: true,
    },
    musicEnabled: true,
    effectsEnabled: false,
  },
  {
    userId: "4",
    name: "Justin BRACAGE",
    age: "9",
    icon: "turtle.png",
    conditions: ["Visual Processing Disorder"],
    userConfig: {
      showsAnswer: true,
      addition: false,
      subtraction: false,
      multiplication: false,
      division: false,
      rewrite: true,
      encryption: false,
      word: true,
    },
    musicEnabled: false,
    effectsEnabled: false,
  }
];