module.exports = [
  {
    userId: "1",
    name: "Eli KOPTER",
    age: "9",
    icon: "red_fish.png",
    conditions: ["Dyslexia", "ADHD"],
    userConfig: {
      showAnswer: true,
      addition: true,
      subtraction: true,
      multiplication: true,
      division: true,
      rewrite: true,
      encryption: true,
      word: true,
      nombresDeQuestion: 7,
      questionFrequency: {
        addition: 0.25,
        subtraction: 0.25,
        multiplication: 0.25,
        division: 0.25
      }
    },
    musicEnabled: false,
    effectsEnabled: true,
    limitedLives: true,
    showScore: false,
    selectedPlayerImage: '/assets/images/game/player/yellow_fish.png',
    money: 0,
    unlockedAvatars: ['yellow_fish'],
  },
  {
    userId: "2",
    name: "Judas BRICOT",
    age: "9",
    icon: "yellow_fish.png",
    conditions: ["Dyscalculia"],
    userConfig: {
      showAnswer: true,
      addition: true,
      subtraction: true,
      multiplication: false,
      division: false,
      rewrite: true,
      encryption: false,
      word: false,
    },
    musicEnabled: true,
    effectsEnabled: true,
    limitedLives: true,
    showScore: true,
    selectedPlayerImage: '../../../../frontend/src/assets/images/game/player/yellow_fish.png',
    money: 0,
    unlockedAvatars: ['yellow_fish'],
  },
  {
    userId: "3",
    name: "Lucie FERT",
    age: "9",
    icon: "blue_fish.png",
    conditions: [],
    userConfig: {
      showAnswer: false,
      addition: true,
      subtraction: true,
      multiplication: true,
      division: true,
      rewrite: true,
      encryption: true,
      word: true,
    },
    musicEnabled: true,
    effectsEnabled: false,
    limitedLives: true,
    showScore: true,
    selectedPlayerImage: '../../../../frontend/src/assets/images/game/player/yellow_fish.png',
    money: 0,
    unlockedAvatars: ['yellow_fish'],
  },
  {
    userId: "4",
    name: "Justin BRACAGE",
    age: "9",
    icon: "turtle.png",
    conditions: ["Visual Processing Disorder"],
    userConfig: {
      showAnswer: true,
      addition: false,
      subtraction: false,
      multiplication: false,
      division: false,
      rewrite: true,
      encryption: false,
      word: true,
    },
    musicEnabled: false,
    effectsEnabled: false,
    limitedLives: true,
    showScore: true,
    selectedPlayerImage: '../../../../frontend/src/assets/images/game/player/yellow_fish.png',
    money: 0,
    unlockedAvatars: ['yellow_fish'],
  },
];