const QuestionNotion = {
  MULTIPLICATION: 'MULTIPLICATION',
  ENCRYPTION: 'ENCRYPTION',
  ADDITION: 'ADDITION',
  SUBTRACTION: 'SUBTRACTION',
  DIVISION: 'DIVISION',
  REWRITE: 'REWRITE',
};

module.exports = { QuestionNotion };
